'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
      return queryInterface.bulkInsert('Spots', [
        {
          userId: 1,
          address: '123 Princess Peach Street',
          city: 'Toad Town',
          state: 'Toadifornia',
          country: 'Mushroom Kingdom',
          series: 'Super Mario Bros',
          description: 'Princess Peach\'s Castle is the home of Princess Peach, and the centerpiece of Toad Town. We are the hub of many world in the surrounding location, and all you need to do is jump into one of the plethora of paintings, and enjoy many different worlds. We are star powered, and please enjoy the stain-glass portrait of the princess. ',
          name: 'Princess Peach\'s Castle',
          price: 690,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091228/airPvP/1-1_frkfzb.jpg',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091232/airPvP/1-2_wi6olj.png',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091229/airPvP/1-3_c18wf3.jpg',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091229/airPvP/1-4_f979ej.jpg',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 1,
          address: '123 Koopa Street',
          city: 'Koopa Town',
          state: 'Bowsertopia',
          country: 'Koopa Kingdom',
          series: 'Super Mario Bros',
          description: 'Bowser\'s Castle is located in the capital of Koopa Kingdom. It is surrounded by beautiful volcanoes, wastelands, dark clouds, forests, glaciers, and castle ruins. Wait, none of that actually sounds really good. At least maybe you can get a glimpse of Princess Peach after Bowser\'s multiple kidnapping attempts?',
          name: 'Bowser\'s Castle',
          price: 700,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091230/airPvP/2-1_k3yzno.jpg',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091231/airPvP/2-2_kchohq.jpg',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091230/airPvP/2-3_ytj1jr.jpg',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091232/airPvP/2-4_udlu5q.jpg',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 1,
          address: '123 Boo Street',
          city: 'Modesto',
          state: 'Pennsylboonia',
          country: 'Koopa Kingdom',
          series: 'Super Mario Bros',
          description: 'This mansion has five rooms including a foyer, nursery, kitchen , study, and ballroom. You can party as hard as you want in this mansion, as it will rebuild itself and return to it\'s original state. I hope you don\'t mind ghosts tho. Sometimes they will trap you in paintings. No big deal.',
          name: 'Luigi\'s Mansion',
          price: 800,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091234/airPvP/3-1_uhrlm1.webp',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091234/airPvP/3-2_iuroql.png',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091236/airPvP/3-3_pl6plg.jpg',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091229/airPvP/3-4_wcupsk.jpg',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 2,
          address: '123 DDD Street',
          city: 'Mt. Dedede',
          state: 'Ideeho',
          country: 'Dream Land',
          series: 'Kirby',
          description: 'Castle DeDeDe is located at the peak of Mt. Dedede. There are four doors that leads down to four different bosses. The windows of the small fortress have iconic scowling eyes, and turn to sad-looking eyes everytime Kirby beats King Dedede.',
          name: 'Castle DeDeDe',
          price: 1000,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091228/airPvP/4-1_x6nqpe.webp',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091246/airPvP/4-2_nqxiie.png',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091229/airPvP/4-3_dv9mtj.webp',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091230/airPvP/4-4_eyx07d.webp',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 2,
          address: '123 Hey Listen Street',
          city: 'Modesto',
          state: 'New Hyrule',
          country: 'Hyrule',
          series: 'The Legend of Zelda',
          description: 'Hyrule Castle is usually directly in the center of Hyrule\'s geographical layout in each game, serving as the crown jewel of the kingdom.It is often one of the most important places for Link during his numerous adventures in Hyrule and many times is the site of the final confrontations, usually serving as a level or dungeon of sorts.As the seat of Hyrule\'s government, the Castle has been the location of multiple conflicts and has been the subject of invasion more than once throughout its depiction in The Legend of Zelda series.',
          name: 'Hyrule Castle',
          price: 900,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091230/airPvP/5-1_vbzye2.jpg',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091234/airPvP/5-2_rtm1zh.webp',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091242/airPvP/5-3_ffsyyx.png',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091234/airPvP/5-4_ihlhrj.webp',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 2,
          address: '123 Middle of Nowhere',
          city: 'In the middle of the sea',
          state: 'Pacific Ocean',
          country: 'United States',
          series: 'Animal Crossing',
          description: 'James Island is a nice and quiet deserted island with just the amenities you need. The locals are nice, and will send you tasks and pay you in bells. Only downside is the mayor is currently working very hard on improving the island. The other day, he dug holes all over the island saying he wanted to get the rocks all in one area.',
          name: 'James Island',
          price: 200,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091236/airPvP/6-1_pmq12v.webp',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091236/airPvP/6-4_r2q7ws.jpg',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091235/airPvP/6-3_swafxp.webp',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091234/airPvP/6-3_ohrljh.jpg',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 3,
          address: '123 Papou Street',
          city: 'Destiny Islands',
          state: 'Destiny Islands',
          country: 'United States',
          series: 'Kingdom Hearts',
          description: 'The islands are an archipelago that consists of several land masses. Close enough to the main islands to be reached by small boats is an island that several of the characters visit for recreation. The keyhole of the islands is located here in a small cave which Riku discovered as a boy. The main island is a regular town with a school. A superstition of the island is the power of the paopu fruit which is said to bind together the destinies of any two people who share one.',
          name: 'Destiny Island',
          price: 300,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091238/airPvP/7-1_oopkvc.jpg',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091236/airPvP/7-2_mjsecv.webp',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091238/airPvP/7-3_ocnpyv.jpg',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091249/airPvP/7-4_o4pzkk.png',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 3,
          address: '123 We haven\'t seen you since CoM Street',
          city: 'Traverse Town',
          state: 'Disney World',
          country: 'United States',
          series: 'Kingdom Hearts',
          description: 'Traverse Town has architecture is reminiscent of the High Victorian style popular in England during the 19th century. It serves as a home for people who manage to escape the destruction of their own worlds by unknowingly drifting through "corridors of darkness". Traverse Town is separated into three major districts. The First District is generally devoid of Heartless and houses various shops. The Second District contains the bell tower, a gizmo shop, and a small hotel. The world\'s keyhole is located in the fountain in this district.The Dalmatians\' house is also accessible here. The Third District is a plaza that has been overrun with Heartless. This district leads to a guarded alcove where Merlin lives.',
          name: 'Traverse Town',
          price: 500,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091257/airPvP/8-2_ra70wi.png',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091237/airPvP/8-1_wovspt.jpg',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091240/airPvP/8-3_bxnzjy.jpg',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091241/airPvP/8-4_oejdhk.jpg',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 3,
          address: '123 Final Fantasy Street',
          city: 'Radiant Gardent',
          state: 'Heartless World',
          country: 'United States',
          series: 'Kingdom Hearts',
          description: 'Radiant Garden is dominated by Ansem\'s castle which is now derelict with the surrounding town covered in ice. A combination of clockwork mechanisms and magic operate lifts, which are used to traverse the castle. Underneath the castle entrance are the dungeons and a series of waterways which provide plumbing throughout the castle. A library upstairs contains knowledge collected by the castle\'s former scientists. In the deepest part of the castle is a factory where Heartless were once manufactured, also serving as an secret entrance to the Chamber of Repose where Aqua\'s armor and Keyblade are located (having left alongside Xehanort by the Keyblade master herself when he was found). Aside from the castle itself while in repairs, the restored town at its foot serves as the base of operations for the Hollow Bastion Restoration Committee',
          name: 'Hollow Bastion',
          price: 900,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091246/airPvP/9-2_eeblwz.jpg',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091242/airPvP/9-1_t5zikh.jpg',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091249/airPvP/9-3_yn0esu.jpg',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091254/airPvP/9-4_gzdg6d.jpg',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 1,
          address: '13 Xehanort Street',
          city: 'Land of Departure',
          state: 'Disney Land',
          country: 'United States',
          series: 'Kingdom Hearts',
          description: 'Castle Oblivion is dominated by the use of cards. When entering the castle, one\'s memories and abilities are quantified into cards.Castle Oblivion\'s floors can be transmuted into different forms and layouts through the use of "world cards" derived from one\'s memories, as well as "map cards" which determine the properties of individual rooms.World cards based on Traverse Town, Wonderland, Olympus Coliseum, Agrabah, Halloween Town, Monstro, Atlantica, Never Land, Hollow Bastion, 100 Acre Wood, Twilight Town, and Destiny Islands have been created from Sora\'s memories. After losing its members, the Organization abandoned Castle Oblivion, though Axel was sent to it in order to find the entrance to the Chamber of Wakening.',
          name: 'Castle Oblivion',
          price: 700,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091248/airPvP/10-1_ekauvs.webp',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091248/airPvP/10-2_xvqivb.jpg',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091249/airPvP/10-3_mry56g.jpg',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091251/airPvP/10-4_ysmev0.jpg',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 1,
          address: '123 Xion Street',
          city: 'Twilight Town',
          state: 'California',
          country: 'United States',
          series: 'Kingdom Hearts',
          description: 'Twilight Town is split into two parts, the shopping district and the residential district, with a train and underground tunnel system that connects the two.There are plenty of stores here, including an accessory shop, as well as lots of houses lined up.Twilight Town is among other worlds to be found between light and darkness, being a perfect balance between the two realms.',
          name: 'Twilight Town',
          price: 300,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091251/airPvP/11-1_h4lmih.webp',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091250/airPvP/11-2_pwhgav.jpg',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091252/airPvP/11-3_thbxge.jpg',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091251/airPvP/11-4_xvepih.jpg',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 1,
          address: '123 Yami Street',
          city: 'Darkness',
          state: 'Darkness',
          country: 'The World That Never Was',
          series: 'Kingdom Hearts',
          description: 'The Castle That Never Was is situated next to the realm of darkness in an in-between realm. It also houses the headquarters of Organization XIII, the Castle That Never Was, which is portrayed as a huge white castle decorated with the emblem of the Nobodies, in addition to Dark City, a deserted metropolis of skyscrapers. The most distinct feature of this world of perpetual night is a large, heart-shaped moon—Kingdom Hearts.',
          name: 'The Castle That Never Was',
          price: 900,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091252/airPvP/12-1_utbpxx.webp',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091252/airPvP/12-2_uwmxje.webp',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091252/airPvP/12-3_ig5kpg.webp',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091253/airPvP/12-4_etfihu.webp',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 2,
          address: '123 Robotnik Street',
          city: 'Green Hills',
          state: 'Green Onions',
          country: 'United States',
          series: 'Sonic the Hedgehog',
          description: 'Green Hill Zone is a picturesque mountain paradise with green fields and beautiful blue lakes. It features large waterfall vistas, palm trees, rotating flowers, flora in various colors and totem poles of unknown origin. Perhaps most distinctively, the soil is checkered brown, and most of the local plant life appears to have unfamiliar geometric appearances to it. As shown during the Sky Base Zone incident and the Time Eater incident, Green Hill Zone also has a series of dark, brown caves underneath it, which have small lakes and ponds of water in them.',
          name: 'Green Hill Zone',
          price: 100,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091282/airPvP/13-1_sl0boi.bmp',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091258/airPvP/13-2_zko2y6.png',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091257/airPvP/13-3_nwkqj4.webp',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091258/airPvP/13-4_lvrxfe.png',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 2,
          address: '123 Brad Street',
          city: 'Minecraft',
          state: 'On My Computer',
          country: 'United States',
          series: 'Minecraft',
          description: 'Worlds are split into three dimensions, which are in turn composed of blocks of various sizes, usually either cubic or composed of one or more cuboids, or of flat plane images, all of which are arranged in a Euclidean grid. Fluids, entities and particles also exist within these worlds, and certain locations of the world can possess biomes and different levels of light. Blocks and entities can possess other attributes such as items, status effects and, by extension, enchantments. Various structures can also generate inside worlds, sometimes containing chests with loot inside.',
          name: 'Minecraft World',
          price: 999,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091257/airPvP/14-1_gwjs7l.jpg',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091260/airPvP/14-2_jaojm2.jpg',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091260/airPvP/14-3_om72h4.jpg',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091273/airPvP/14-4_w42xar.webp',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 2,
          address: '123 Alec Street',
          city: 'Minesweeper',
          state: 'On My Computer',
          country: 'United States',
          series: 'Minesweeper',
          description: 'A pretty cool place if you don\'t step on a mine and die.',
          name: 'Minesweeper world',
          price: 999,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091260/airPvP/15-1_nwyx65.webp',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091260/airPvP/15-2_kwyfzu.webp',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091261/airPvP/15-3_oclt6s.webp',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091261/airPvP/15-4_dqi9kk.webp',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 3,
          address: '123 Blizzard Street',
          city: 'Irvine',
          state: 'California',
          country: 'United States',
          series: 'Overwatch',
          description: 'Where you took your first steps in Azeroth. Where you confronted the Lord of Terror himself. Where you spawned your first zergling rush. Sometimes, epic memories can only be made in an epic world. Your adventure. Your community. Your memories. See them come alive in your world. Blizzard World! Come and visit Blizzard World. New adventures are waiting for you.',
          name: 'Blizzard World',
          price: 900,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091262/airPvP/16-1_qljaps.jpg',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091263/airPvP/16-2_avafax.jpg',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091275/airPvP/16-3_g9nlli.jpg',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091275/airPvP/16-4_gfbvb5.jpg',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 3,
          address: '123 Pikachu Street',
          city: 'Pallet Town',
          state: 'Kanto',
          country: 'Japan',
          series: 'Pokémon',
          description: 'Pallet Town is a small town located in southwestern Kanto. The town has two exits. To the north is Route 1, leading to Viridian City. To the south is Route 21, a water route leading to Cinnabar Island. Pallet Town\'s population is 8, making it the smallest town in Kanto due to its lack of amenities like a gym or Pokemon Center.',
          name: 'Pallet Town',
          price: 200,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091264/airPvP/17-1_wkz78e.jpg',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091266/airPvP/17-2_jwjpql.jpg',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091266/airPvP/17-3_dvukwx.webp',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091268/airPvP/17-4_ohbwsb.webp',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 3,
          address: 'Route 23',
          city: 'Victory Road',
          state: 'Kanto',
          country: 'Japan',
          series: 'Pokémon',
          description: 'On the ground floor is a combined Poké Mart and Pokémon Center. This is the last safe stop before Trainers make their way up to the upper floors, therefore, Trainers can purchase and stock up on items, as well as heal their Pokémon before leaving. There are a number of things a player can do on this floor. A Pokémon Center Nurse heals all status conditions, recharges HP and PP of all party Pokémon, free of charge. The nurse is located at the main counter just as the player enters Indigo Plateau. It also hosts the Cable Club and the Union Room, which facilitates multiplayer gameplay and link players to battle and trade one another. Trainers also have access to a PC. Trainers can also buy items from the Poké Mart. The Poké Mart stocks rare items that can only be found in Indigo Plateau.',
          name: 'Indigo Plateau',
          price: 500,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091268/airPvP/18-1_ikc2kh.webp',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091269/airPvP/18-2_zxjpie.png',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091270/airPvP/18-3_tfzv8j.jpg',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091270/airPvP/18-4_zmjkto.jpg',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 1,
          address: '123 Dayton Street',
          city: 'In my toybox',
          state: 'California',
          country: 'United States',
          series: 'Super Smash Bros',
          description: 'Final Destination consists of a single platform with ledges that can be grabbed. Compared to previous iterations, it appears to have a crystalline texture with mechanical elements. Its background primarily travels through three different nebulae: a cream-colored one with a black hole, a green one with psychedelic crystalline objects floating in the background, and a fiery orange one partially obscured by blue clouds.[1] This iteration of Final Destination is shorter than in past games, now being the same length as Battlefield. This is also true of all Ω forms. Anytime the stage is loaded, it will start on a different background.',
          name: 'Final Destination',
          price: 800,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091271/airPvP/19-1_f3ttdd.jpg',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091278/airPvP/19-2_zveo5h.png',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091274/airPvP/19-3_gdplkz.webp',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091275/airPvP/19-4_umhnab.jpg',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          userId: 2,
          address: 'Over 1000 Hours Street',
          city: 'Radiant',
          state: 'California',
          country: 'United States',
          series: 'Dota 2',
          description: 'The Map is the playing field for all Dota 2 matches. It is comprised of two sides, one for the Radiant icon.png Radiant faction, and one for the Dire icon.png Dire faction. To win, players must destroy the opposing side\'s Ancient, an important building at the center of each team\'s base.',
          name: 'Dota 2 Map',
          price: 100,
          img1: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091277/airPvP/20-1_znkans.jpg',
          img2: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091278/airPvP/20-2_yjbnls.jpg',
          img3: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091279/airPvP/20-3_z4smay.jpg',
          img4: 'https://res.cloudinary.com/jameschenn/image/upload/v1649091280/airPvP/20-4_ebnx8j.jpg',
          createdAt: new Date(),
          updatedAt: new Date()
        },
      ], {});
  },

  down: (queryInterface, Sequelize) => {

      return queryInterface.bulkDelete('Spots', null, {});

  }
};
