'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {

      return queryInterface.bulkInsert('Reviews', [
        { userId: 1, spotId: 1, review: 'This was a great location to have a brawl, and then have cake with the princess. Would come visit again.', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 1, review: 'I gotta stop eating all these mushrooms all over the place. I\'m starting to see some weird things 🤯', rating: 2, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 1, review: 'Lots of secrets within the castle! I found a slide behind one of the stained glass windows!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 2, review: 'Too many obstacles all over the place, and it\'s literally surrounded by fire. It\'s way too hot here...', rating: 1, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 2, review: 'I was surprised to find this location came with a princess, but a plump italian plumber jumped in and kidnapped her in the middle of my stay!', rating: 2, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 2, review: 'I\'m totally not Bowser... This is a great place to stay!!', rating: 3, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 3, review: 'Nice place during the day, but I left in the middle of the night because I was too scared. OWNER DOES NOT PROVIDE REFUNDS!', rating: 1, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 3, review: '👻👻👻', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 3, review: 'Too many ghosts. Couldn\'t sleep...', rating: 1, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 4, review: 'A certain pink blob flew around and ate everything! I was starving throughout my trip.', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 4, review: 'Lots of great locations nearby to visit. I would come back to visit some things I missed.', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 4, review: 'Lots of cute round creatures everywhere. I wonder how they taste. 🤔', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 5, review: 'This area is way too big. I didn\'t have time to explore everything.', rating: 3, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 5, review: 'Mod 5 sure loves this series. Shoutout to group 1. The hero of time!!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 5, review: 'This guy in a green tunic barged into my house and smashed all my pots!!', rating: 1, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 6, review: 'This guy\'s island is the best!! I need to go get his friend code!!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 6, review: 'The person who built up this island must\'ve put in his heart and soul into it. He has all his rocks in the same place too!!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 6, review: 'This island needs some maintenance. It feels like it hasn\'t been touched in months!!', rating: 3, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 7, review: 'This was the perfect location to visit for their 20th anniversary!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 7, review: 'I shared a papou fruit with this girl, and now she won\'t leave me alone!', rating: 4, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 7, review: 'Nice relaxing location to relax in. I\'m sure the friends I made on the island are waiting for me to come back!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 8, review: 'Lots of great amenities and shops in the surrounding area. Why do they call it munny instead of money?', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 8, review: 'A lot of people were turning into little shadow looking beings. I wonder where their hearts flew off to. 🤔', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 8, review: 'Lots of areas. Very easy to get lost.', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 9, review: 'Such an iconic location! Probably the best stage ever!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 9, review: 'This location feels like it has a lot of history. I hope they flesh out the story more!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 9, review: 'Did I really just a dog and duck ditch a boy for a key?', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 10, review: 'Too many stairs... my legs are tired.', rating: 3, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 10, review: 'Huh? What happened? It\'s like I lost my memory...', rating: 4, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 10, review: 'Went into a castle, came out with a bunch of cards in my pocket.', rating: 4, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 11, review: 'A nice quiet town. I love sea salt ice cream!!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 11, review: 'Would come back here again.', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 11, review: 'Walking distance to the new hotest resturant in town!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 12, review: 'Very dark and rainy location. Lots of shadows.', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 12, review: 'This location felt like a maze. I felt like I was going to get attacked in the shadows.', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 12, review: 'Why does everyone look tall, dark, and handsome here?', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 13, review: 'Lots of rings laying around this location. I wonder if my girlfriend would like one?', rating: 4, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 13, review: 'Time seemed to stop every now and then here. I guess I had that much fun here.', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 13, review: 'Very nice location filled with cute critters stuffed in robots.', rating: 3, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 14, review: 'A lot of creepers at this location. They seem hostile, do not go near them.', rating: 2, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 14, review: 'Very blocky location.', rating: 3, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 14, review: 'Got really creative, and deconstructed and rebuilt a lot of the owner\'s property. He did not appreciate that...', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 15, review: 'I stepped on a mine at this location and lost my leg.', rating: 1, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 15, review: 'I miss watching Alec play minesweeper', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 15, review: 'Watch your step at this location!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 16, review: 'More fun than Disneyland!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 16, review: 'I had a great time at this location', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 16, review: 'Loved the theme of this location!1', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 17, review: 'Truly an OG location.', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 17, review: 'Seemed kinda empty. This location had nothing at all in this town except an old professor and some 10 year old boys.', rating: 2, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 17, review: 'Don\'t go into the grass! You can be attacked by wild Pokemon!', rating: 3, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 18, review: 'Lots of tough Pokemon at this location.', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 18, review: 'Tried to get pass security, but I didn\'t have enough badges...', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 18, review: 'This location included a cave with lots of tough Pokemon to train against!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 19, review: 'This stage is literally the GOAT!!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 19, review: 'I had a great time smashing some opponents here!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 19, review: 'Perfection!', rating: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, spotId: 20, review: 'Creeps and enemy heroes kept trying to attack me at this location. Do not recommend.', rating: 1, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, spotId: 20, review: 'This location is way too toxic.', rating: 1, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, spotId: 20, review: 'I tried to give this location another chance, and now I remember why I left.', rating: 1, createdAt: new Date(), updatedAt: new Date() },
      ], {});
  },

  down: (queryInterface, Sequelize) => {

      return queryInterface.bulkDelete('Reviews', null, {});
  }
};
